# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Add 2 numeric vectors
#'
#' @param x,y numeric vectors
#'
#' @return numeric vector
#'
add_rcpp <- function(x, y) {
    .Call(`_simplercpp_add_rcpp`, x, y)
}

#' Multiply 2 numeric vectors
#'
#' @param x,y numeric vectors
#'
#' @return numeric vector
#'
mul_rcpp <- function(x, y) {
    .Call(`_simplercpp_mul_rcpp`, x, y)
}

